# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\sksgm\OneDrive\문서\GitHub\NEIS_Macro\src\views\ui\main.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainApp(object):
    def setupUi(self, MainApp):
        MainApp.setObjectName("MainApp")
        MainApp.resize(500, 900)
        MainApp.setMinimumSize(QtCore.QSize(500, 500))
        MainApp.setMaximumSize(QtCore.QSize(500, 900))
        MainApp.setStyleSheet("QMainWindow\n"
"{\n"
"    background: transparent; \n"
"}\n"
"#MainApp, #black, #main_widget {\n"
"    background: white;\n"
"    border-radius: 30px;\n"
"    border: 1px solid gainsboro;\n"
"}\n"
"QObject {\n"
"    background: transparent; \n"
"    margin: 0px; \n"
"    padding:0px;\n"
"    font: 20px \"Pretendard\";\n"
"    font-weight: bold;\n"
"    color: black;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainApp)
        self.centralwidget.setObjectName("centralwidget")
        self.black = QtWidgets.QWidget(self.centralwidget)
        self.black.setEnabled(False)
        self.black.setGeometry(QtCore.QRect(0, 0, 500, 900))
        self.black.setStyleSheet("#black {\n"
"    background: rgba(0,0,0,180);\n"
"}\n"
"#infobox {background: white; border-radius: 20px;}\n"
"#infobox_title {font:17px; color: \"#ff3227\"}\n"
"#infobox_detail {font:17px; color: \"#8b8b8f\"}\n"
"#infobox_confirm {background: transparent; font: 20px \"나눔스퀘어 ExtraBold\"; color:rgb(52, 120, 245)}\n"
"#infobox_confirm:hover {color:rgba(52, 120, 245, 100)}")
        self.black.setObjectName("black")
        self.infobox = QtWidgets.QWidget(self.black)
        self.infobox.setGeometry(QtCore.QRect(60, 270, 381, 201))
        self.infobox.setObjectName("infobox")
        self.line = QtWidgets.QFrame(self.infobox)
        self.line.setGeometry(QtCore.QRect(0, 120, 381, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.infobox_title = QtWidgets.QLabel(self.infobox)
        self.infobox_title.setGeometry(QtCore.QRect(0, 40, 381, 20))
        self.infobox_title.setTextFormat(QtCore.Qt.AutoText)
        self.infobox_title.setAlignment(QtCore.Qt.AlignCenter)
        self.infobox_title.setObjectName("infobox_title")
        self.infobox_confirm = QtWidgets.QPushButton(self.infobox)
        self.infobox_confirm.setGeometry(QtCore.QRect(0, 128, 381, 71))
        self.infobox_confirm.setObjectName("infobox_confirm")
        self.infobox_detail = QtWidgets.QLabel(self.infobox)
        self.infobox_detail.setGeometry(QtCore.QRect(0, 70, 381, 20))
        self.infobox_detail.setTextFormat(QtCore.Qt.AutoText)
        self.infobox_detail.setAlignment(QtCore.Qt.AlignCenter)
        self.infobox_detail.setObjectName("infobox_detail")
        self.main_widget = QtWidgets.QWidget(self.centralwidget)
        self.main_widget.setGeometry(QtCore.QRect(0, 0, 500, 900))
        self.main_widget.setObjectName("main_widget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.main_widget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 30)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.window = QtWidgets.QWidget(self.main_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.window.sizePolicy().hasHeightForWidth())
        self.window.setSizePolicy(sizePolicy)
        self.window.setObjectName("window")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.window)
        self.horizontalLayout_2.setContentsMargins(40, 10, 20, 10)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.window_title = QtWidgets.QLabel(self.window)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.window_title.sizePolicy().hasHeightForWidth())
        self.window_title.setSizePolicy(sizePolicy)
        self.window_title.setText("")
        self.window_title.setObjectName("window_title")
        self.horizontalLayout_2.addWidget(self.window_title)
        self.window_buttons = QtWidgets.QWidget(self.window)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.window_buttons.sizePolicy().hasHeightForWidth())
        self.window_buttons.setSizePolicy(sizePolicy)
        self.window_buttons.setStyleSheet("QPushButton {\n"
"    border-radius: 7px; \n"
"    font: 10px \"FontAwesome\";\n"
"    color: rgb(112, 43, 40);\n"
"}\n"
"QPushButton:hover {\n"
"    color: rgba(112, 43, 40, 100);\n"
"}")
        self.window_buttons.setObjectName("window_buttons")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.window_buttons)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.window_minimum = QtWidgets.QPushButton(self.window_buttons)
        self.window_minimum.setMinimumSize(QtCore.QSize(14, 14))
        self.window_minimum.setMaximumSize(QtCore.QSize(14, 14))
        self.window_minimum.setStyleSheet("QPushButton {\n"
"    background: rgb(255, 196, 48);\n"
"}\n"
"QPushButton:hover {\n"
"    background: rgba(255, 196, 48, 100);\n"
"}")
        self.window_minimum.setObjectName("window_minimum")
        self.horizontalLayout.addWidget(self.window_minimum)
        self.window_close = QtWidgets.QPushButton(self.window_buttons)
        self.window_close.setMinimumSize(QtCore.QSize(14, 14))
        self.window_close.setMaximumSize(QtCore.QSize(14, 14))
        self.window_close.setStyleSheet("QPushButton {\n"
"    background: rgb(255, 98, 89)\n"
"}\n"
"QPushButton:hover {\n"
"    background: rgba(255, 98, 89, 100)\n"
"}")
        self.window_close.setObjectName("window_close")
        self.horizontalLayout.addWidget(self.window_close)
        self.horizontalLayout_2.addWidget(self.window_buttons)
        self.verticalLayout_3.addWidget(self.window)
        self.Form_widget = QtWidgets.QWidget(self.main_widget)
        self.Form_widget.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Form_widget.sizePolicy().hasHeightForWidth())
        self.Form_widget.setSizePolicy(sizePolicy)
        self.Form_widget.setMinimumSize(QtCore.QSize(500, 120))
        self.Form_widget.setMaximumSize(QtCore.QSize(16777215, 140))
        self.Form_widget.setAutoFillBackground(False)
        self.Form_widget.setStyleSheet("/* Form stackedwidget */\n"
"#Form_stackedWidget {\n"
"    background-color: rgb(245, 245, 248);\n"
"    border-radius: 10px;\n"
"    padding: 0px 35px;\n"
"}\n"
"\n"
"/* Form downloader margin */\n"
"#Form_widget {\n"
"    margin:0px;\n"
"    padding:20px\n"
"}\n"
"\n"
"/* Form\'s Grid */\n"
"#Form_download_grid,\n"
"#Form_info_grid {\n"
"    margin:0px;\n"
"    padding:0px 0px;\n"
"}\n"
"\n"
"/* Form\'s Button */\n"
"#Form_downbar_get,\n"
"#Form_info_get {\n"
"    border-radius:15px; \n"
"    width: 50px; \n"
"    height: 30px;\n"
"    background:rgb(52, 120, 245); \n"
"    font: 16px;\n"
"    font-weight: bold; \n"
"    color: #ffffff\n"
"}\n"
"#Form_downbar_get:hover,\n"
"#Form_info_get:hover {\n"
"    background: rgba(52, 120, 245, 100);\n"
"    color: #ffffff\n"
"}\n"
"\n"
"/* Form\'s widget titles */\n"
"#Form_downbar_id,\n"
"#Form_info_id {\n"
"    font: 17px;\n"
"    font-weight: 600;\n"
"}\n"
"#Form_downbar_subtitle,\n"
"#Form_info_subtitle {\n"
"    font: 13px;\n"
"    color: #989799\n"
"}\n"
"#Form_downbar_icon,\n"
"#Form_info_icon {\n"
"    border-radius: 5px; \n"
"    border: 1px solid #eeeef0;\n"
"    background: #f7f7f7;\n"
"    margin: 5px;\n"
"}")
        self.Form_widget.setObjectName("Form_widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.Form_widget)
        self.verticalLayout.setContentsMargins(60, 20, 60, 10)
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.FormName = QtWidgets.QLabel(self.Form_widget)
        self.FormName.setMaximumSize(QtCore.QSize(16777215, 40))
        self.FormName.setObjectName("FormName")
        self.verticalLayout.addWidget(self.FormName)
        self.Form_stackedWidget = QtWidgets.QStackedWidget(self.Form_widget)
        self.Form_stackedWidget.setMinimumSize(QtCore.QSize(0, 70))
        self.Form_stackedWidget.setStyleSheet("")
        self.Form_stackedWidget.setObjectName("Form_stackedWidget")
        self.Form_downbar_grid = QtWidgets.QWidget()
        self.Form_downbar_grid.setObjectName("Form_downbar_grid")
        self.Searchbar_layout = QtWidgets.QHBoxLayout(self.Form_downbar_grid)
        self.Searchbar_layout.setContentsMargins(0, 0, 0, 0)
        self.Searchbar_layout.setSpacing(0)
        self.Searchbar_layout.setObjectName("Searchbar_layout")
        self.Form_downbar_icon = QtWidgets.QLabel(self.Form_downbar_grid)
        self.Form_downbar_icon.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Form_downbar_icon.sizePolicy().hasHeightForWidth())
        self.Form_downbar_icon.setSizePolicy(sizePolicy)
        self.Form_downbar_icon.setMinimumSize(QtCore.QSize(56, 0))
        self.Form_downbar_icon.setMaximumSize(QtCore.QSize(56, 60))
        self.Form_downbar_icon.setText("")
        self.Form_downbar_icon.setPixmap(QtGui.QPixmap(":/img/assets/Microsoft_Excel-Logo.wine.svg"))
        self.Form_downbar_icon.setScaledContents(True)
        self.Form_downbar_icon.setIndent(-1)
        self.Form_downbar_icon.setObjectName("Form_downbar_icon")
        self.Searchbar_layout.addWidget(self.Form_downbar_icon)
        self.Form_downbar_info_widget = QtWidgets.QWidget(self.Form_downbar_grid)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Form_downbar_info_widget.sizePolicy().hasHeightForWidth())
        self.Form_downbar_info_widget.setSizePolicy(sizePolicy)
        self.Form_downbar_info_widget.setObjectName("Form_downbar_info_widget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.Form_downbar_info_widget)
        self.verticalLayout_4.setContentsMargins(-1, 16, -1, 16)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.Form_downbar_id = QtWidgets.QLabel(self.Form_downbar_info_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Form_downbar_id.sizePolicy().hasHeightForWidth())
        self.Form_downbar_id.setSizePolicy(sizePolicy)
        self.Form_downbar_id.setObjectName("Form_downbar_id")
        self.verticalLayout_4.addWidget(self.Form_downbar_id)
        self.Form_downbar_subtitle = QtWidgets.QLabel(self.Form_downbar_info_widget)
        self.Form_downbar_subtitle.setObjectName("Form_downbar_subtitle")
        self.verticalLayout_4.addWidget(self.Form_downbar_subtitle)
        self.Searchbar_layout.addWidget(self.Form_downbar_info_widget)
        self.Form_downbar_get = QtWidgets.QPushButton(self.Form_downbar_grid)
        self.Form_downbar_get.setMinimumSize(QtCore.QSize(70, 40))
        self.Form_downbar_get.setMaximumSize(QtCore.QSize(70, 40))
        self.Form_downbar_get.setObjectName("Form_downbar_get")
        self.Searchbar_layout.addWidget(self.Form_downbar_get)
        self.Form_stackedWidget.addWidget(self.Form_downbar_grid)
        self.Form_info_grid = QtWidgets.QWidget()
        self.Form_info_grid.setObjectName("Form_info_grid")
        self.Searchbar2_layout = QtWidgets.QHBoxLayout(self.Form_info_grid)
        self.Searchbar2_layout.setContentsMargins(0, 0, 0, 0)
        self.Searchbar2_layout.setSpacing(0)
        self.Searchbar2_layout.setObjectName("Searchbar2_layout")
        self.Form_info_icon = QtWidgets.QLabel(self.Form_info_grid)
        self.Form_info_icon.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Form_info_icon.sizePolicy().hasHeightForWidth())
        self.Form_info_icon.setSizePolicy(sizePolicy)
        self.Form_info_icon.setMinimumSize(QtCore.QSize(56, 56))
        self.Form_info_icon.setMaximumSize(QtCore.QSize(56, 56))
        self.Form_info_icon.setStyleSheet("padding: 6px; border-radius: 23px;")
        self.Form_info_icon.setText("")
        self.Form_info_icon.setPixmap(QtGui.QPixmap(":/img/assets/info-filled.svg"))
        self.Form_info_icon.setScaledContents(True)
        self.Form_info_icon.setIndent(-1)
        self.Form_info_icon.setObjectName("Form_info_icon")
        self.Searchbar2_layout.addWidget(self.Form_info_icon)
        self.Form_info_widget = QtWidgets.QWidget(self.Form_info_grid)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Form_info_widget.sizePolicy().hasHeightForWidth())
        self.Form_info_widget.setSizePolicy(sizePolicy)
        self.Form_info_widget.setObjectName("Form_info_widget")
        self.Form_info_widget_verticalLayout_4 = QtWidgets.QVBoxLayout(self.Form_info_widget)
        self.Form_info_widget_verticalLayout_4.setContentsMargins(-1, 16, -1, 16)
        self.Form_info_widget_verticalLayout_4.setSpacing(0)
        self.Form_info_widget_verticalLayout_4.setObjectName("Form_info_widget_verticalLayout_4")
        self.Form_info_id = QtWidgets.QLabel(self.Form_info_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Form_info_id.sizePolicy().hasHeightForWidth())
        self.Form_info_id.setSizePolicy(sizePolicy)
        self.Form_info_id.setObjectName("Form_info_id")
        self.Form_info_widget_verticalLayout_4.addWidget(self.Form_info_id)
        self.Form_info_subtitle = QtWidgets.QLabel(self.Form_info_widget)
        self.Form_info_subtitle.setObjectName("Form_info_subtitle")
        self.Form_info_widget_verticalLayout_4.addWidget(self.Form_info_subtitle)
        self.Searchbar2_layout.addWidget(self.Form_info_widget)
        self.Form_info_get = QtWidgets.QPushButton(self.Form_info_grid)
        self.Form_info_get.setMinimumSize(QtCore.QSize(150, 40))
        self.Form_info_get.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setFamily("Pretendard")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.Form_info_get.setFont(font)
        self.Form_info_get.setObjectName("Form_info_get")
        self.Searchbar2_layout.addWidget(self.Form_info_get)
        self.Form_stackedWidget.addWidget(self.Form_info_grid)
        self.verticalLayout.addWidget(self.Form_stackedWidget)
        self.verticalLayout_3.addWidget(self.Form_widget)
        self.Macro = QtWidgets.QWidget(self.main_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Macro.sizePolicy().hasHeightForWidth())
        self.Macro.setSizePolicy(sizePolicy)
        self.Macro.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Macro.setStyleSheet("/* Macro Scroll Area */\n"
"#Macrobar_scroll {\n"
"    background-color: rgb(245, 245, 248);\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"/* Macro grid */\n"
"#Macrobar_grid {\n"
"    margin: 0px\n"
"}\n"
"\n"
"/* Macro buttons in grid */\n"
"#Macrobar_grid .QWidget {\n"
"    margin: 0px; \n"
"    border-radius: 15px; \n"
"    background: rgba(230, 111, 85, 255);\n"
"}\n"
"#Macrobar_grid .QWidget:hover {\n"
"    background:  rgba(230, 111, 85, 200)\n"
"}\n"
"#Macrobar_grid .QWidget .QLabel {\n"
"    font: 16px;\n"
"    font-weight: bold;\n"
"    color: white;\n"
"}\n"
"#Macrobar_grid .QWidget .QPushButton {\n"
"    background: transparent;\n"
"}\n"
"\n"
"\n"
"/* Macro scrollbar */\n"
"#Macrobar_scroll {\n"
"    margin: 0px; \n"
"    padding: 0px; \n"
"    border: 0px solid;\n"
"}\n"
".QScrollArea .QScrollBar:vertical {\n"
"    border: 0px solid #c3c3c3;\n"
"    background:white;\n"
"    width:10px;\n"
"    margin: 10px 4px 10px 0px;\n"
"}\n"
".QScrollArea .QScrollBar::handle:vertical {\n"
"    min-height: 0px;\n"
"    border: 0px solid red;\n"
"    border-radius: 3px;\n"
"    background-color: #c3c3c3;\n"
"}\n"
".QScrollArea .QScrollBar::add-line:vertical {       \n"
"    height: 0px;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"}\n"
".QScrollArea .QScrollBar::sub-line:vertical {\n"
"    height: 0 px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"}")
        self.Macro.setObjectName("Macro")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.Macro)
        self.verticalLayout_2.setContentsMargins(60, 20, 60, 10)
        self.verticalLayout_2.setSpacing(10)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.MacroName = QtWidgets.QLabel(self.Macro)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MacroName.sizePolicy().hasHeightForWidth())
        self.MacroName.setSizePolicy(sizePolicy)
        self.MacroName.setMaximumSize(QtCore.QSize(16777215, 40))
        self.MacroName.setObjectName("MacroName")
        self.verticalLayout_2.addWidget(self.MacroName)
        self.Macrobar_scroll = QtWidgets.QScrollArea(self.Macro)
        self.Macrobar_scroll.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.Macrobar_scroll.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.Macrobar_scroll.setWidgetResizable(True)
        self.Macrobar_scroll.setObjectName("Macrobar_scroll")
        self.Macrobar_grid = QtWidgets.QWidget()
        self.Macrobar_grid.setGeometry(QtCore.QRect(0, 0, 370, 608))
        self.Macrobar_grid.setStyleSheet("")
        self.Macrobar_grid.setObjectName("Macrobar_grid")
        self.Macrobar_grid_layout = QtWidgets.QGridLayout(self.Macrobar_grid)
        self.Macrobar_grid_layout.setContentsMargins(10, 10, 10, 10)
        self.Macrobar_grid_layout.setSpacing(10)
        self.Macrobar_grid_layout.setObjectName("Macrobar_grid_layout")
        self.Macrobar_scroll.setWidget(self.Macrobar_grid)
        self.verticalLayout_2.addWidget(self.Macrobar_scroll)
        self.verticalLayout_3.addWidget(self.Macro)
        self.Contributor = QtWidgets.QWidget(self.main_widget)
        self.Contributor.setStyleSheet("font: 8px;")
        self.Contributor.setObjectName("Contributor")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.Contributor)
        self.horizontalLayout_3.setContentsMargins(60, 0, 60, 0)
        self.horizontalLayout_3.setSpacing(20)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.Contributor_title = QtWidgets.QLabel(self.Contributor)
        self.Contributor_title.setStyleSheet("font-weight: bold;")
        self.Contributor_title.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Contributor_title.setObjectName("Contributor_title")
        self.horizontalLayout_3.addWidget(self.Contributor_title)
        self.Contributor_content = QtWidgets.QLabel(self.Contributor)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Contributor_content.sizePolicy().hasHeightForWidth())
        self.Contributor_content.setSizePolicy(sizePolicy)
        self.Contributor_content.setMinimumSize(QtCore.QSize(30, 0))
        self.Contributor_content.setObjectName("Contributor_content")
        self.horizontalLayout_3.addWidget(self.Contributor_content)
        self.verticalLayout_3.addWidget(self.Contributor)
        self.prev_page = QtWidgets.QPushButton(self.centralwidget)
        self.prev_page.setGeometry(QtCore.QRect(64, 120, 30, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.prev_page.sizePolicy().hasHeightForWidth())
        self.prev_page.setSizePolicy(sizePolicy)
        self.prev_page.setMinimumSize(QtCore.QSize(30, 30))
        self.prev_page.setMaximumSize(QtCore.QSize(30, 30))
        self.prev_page.setStyleSheet("QPushButton {\n"
"    font: 11px \"FontAwesome\";\n"
"    color: gray;\n"
"}\n"
"QPushButton:hover {\n"
"    color: lightgray;\n"
"}\n"
"")
        self.prev_page.setObjectName("prev_page")
        self.next_page = QtWidgets.QPushButton(self.centralwidget)
        self.next_page.setGeometry(QtCore.QRect(410, 120, 30, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.next_page.sizePolicy().hasHeightForWidth())
        self.next_page.setSizePolicy(sizePolicy)
        self.next_page.setMinimumSize(QtCore.QSize(30, 30))
        self.next_page.setMaximumSize(QtCore.QSize(30, 30))
        self.next_page.setStyleSheet("QPushButton {\n"
"    font: 11px \"FontAwesome\";\n"
"    color: gray;\n"
"}\n"
"QPushButton:hover {\n"
"    color: lightgray;\n"
"}\n"
"")
        self.next_page.setObjectName("next_page")
        MainApp.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainApp)
        self.Form_stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainApp)

    def retranslateUi(self, MainApp):
        _translate = QtCore.QCoreApplication.translate
        MainApp.setWindowTitle(_translate("MainApp", "MainWindow"))
        self.infobox_title.setText(_translate("MainApp", "업로드를 실행할 수 없습니다."))
        self.infobox_confirm.setText(_translate("MainApp", "OK"))
        self.infobox_detail.setText(_translate("MainApp", "나이스가 켜져 있는지 확인해주세요."))
        self.window_minimum.setText(_translate("MainApp", ""))
        self.window_close.setText(_translate("MainApp", ""))
        self.FormName.setText(_translate("MainApp", "새로운 사용의 시작"))
        self.Form_downbar_id.setText(_translate("MainApp", "Macro Forms"))
        self.Form_downbar_subtitle.setText(_translate("MainApp", "업로드를 위한 양식 다운로드"))
        self.Form_downbar_get.setText(_translate("MainApp", "GET"))
        self.Form_info_id.setText(_translate("MainApp", "Tutorial"))
        self.Form_info_subtitle.setText(_translate("MainApp", "사용방법 안내"))
        self.Form_info_get.setText(_translate("MainApp", "사용법 확인하기"))
        self.MacroName.setText(_translate("MainApp", "손쉬운 업로드 갤러리"))
        self.Contributor_title.setText(_translate("MainApp", "Contributor\n"
"Contact"))
        self.Contributor_content.setText(_translate("MainApp", "Gonyo\n"
"worker.gonyo@gmail.com"))
        self.prev_page.setText(_translate("MainApp", ""))
        self.next_page.setText(_translate("MainApp", ""))
from src.views.ui import main_rc