# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\owner\Documents\GitHub\NEIS_Macro\src\views\ui\main.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainApp(object):
    def setupUi(self, MainApp):
        MainApp.setObjectName("MainApp")
        MainApp.resize(500, 900)
        MainApp.setMinimumSize(QtCore.QSize(500, 900))
        MainApp.setMaximumSize(QtCore.QSize(500, 900))
        MainApp.setStyleSheet("QMainWindow\n"
"{\n"
"    background: transparent; \n"
"}\n"
"#MainApp, #black, #main_widget {\n"
"    background: white;\n"
"    border-radius: 30px;\n"
"}\n"
"QObject {\n"
"    background: transparent; \n"
"    margin: 0px; \n"
"    padding:0px;\n"
"    font: 20px \"Pretendard\";\n"
"    font-weight: bold;\n"
"    color: black;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainApp)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.black = QtWidgets.QWidget(self.centralwidget)
        self.black.setEnabled(False)
        self.black.setGeometry(QtCore.QRect(0, 0, 500, 900))
        self.black.setStyleSheet("#black {\n"
"    background: rgba(0,0,0,180);\n"
"}\n"
"#infobox {background: white; border-radius: 20px;}\n"
"#infobox_title {font:17px; color: \"#ff3227\"}\n"
"#infobox_detail {font:17px; color: \"#8b8b8f\"}\n"
"#infobox_confirm {background: transparent; font: 20px \"나눔스퀘어 ExtraBold\"; color:rgb(52, 120, 245)}\n"
"#infobox_confirm:hover {color:rgba(52, 120, 245, 100)}")
        self.black.setObjectName("black")
        self.infobox = QtWidgets.QWidget(self.black)
        self.infobox.setGeometry(QtCore.QRect(60, 270, 381, 201))
        self.infobox.setObjectName("infobox")
        self.line = QtWidgets.QFrame(self.infobox)
        self.line.setGeometry(QtCore.QRect(0, 120, 381, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.infobox_title = QtWidgets.QLabel(self.infobox)
        self.infobox_title.setGeometry(QtCore.QRect(0, 40, 381, 20))
        self.infobox_title.setTextFormat(QtCore.Qt.AutoText)
        self.infobox_title.setAlignment(QtCore.Qt.AlignCenter)
        self.infobox_title.setObjectName("infobox_title")
        self.infobox_confirm = QtWidgets.QPushButton(self.infobox)
        self.infobox_confirm.setGeometry(QtCore.QRect(0, 128, 381, 71))
        self.infobox_confirm.setObjectName("infobox_confirm")
        self.infobox_detail = QtWidgets.QLabel(self.infobox)
        self.infobox_detail.setGeometry(QtCore.QRect(0, 70, 381, 20))
        self.infobox_detail.setTextFormat(QtCore.Qt.AutoText)
        self.infobox_detail.setAlignment(QtCore.Qt.AlignCenter)
        self.infobox_detail.setObjectName("infobox_detail")
        self.main_widget = QtWidgets.QWidget(self.centralwidget)
        self.main_widget.setGeometry(QtCore.QRect(0, 0, 500, 900))
        self.main_widget.setObjectName("main_widget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.main_widget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.window = QtWidgets.QWidget(self.main_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.window.sizePolicy().hasHeightForWidth())
        self.window.setSizePolicy(sizePolicy)
        self.window.setObjectName("window")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.window)
        self.horizontalLayout_2.setContentsMargins(40, 10, 20, 10)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.window_title = QtWidgets.QLabel(self.window)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.window_title.sizePolicy().hasHeightForWidth())
        self.window_title.setSizePolicy(sizePolicy)
        self.window_title.setText("")
        self.window_title.setObjectName("window_title")
        self.horizontalLayout_2.addWidget(self.window_title)
        self.window_buttons = QtWidgets.QWidget(self.window)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.window_buttons.sizePolicy().hasHeightForWidth())
        self.window_buttons.setSizePolicy(sizePolicy)
        self.window_buttons.setStyleSheet("QPushButton {\n"
"    border-radius: 9px; \n"
"    font: 10px \"FontAwesome\";\n"
"    color: rgb(112, 43, 40);\n"
"}")
        self.window_buttons.setObjectName("window_buttons")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.window_buttons)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.minimum = QtWidgets.QPushButton(self.window_buttons)
        self.minimum.setMinimumSize(QtCore.QSize(18, 18))
        self.minimum.setMaximumSize(QtCore.QSize(18, 18))
        self.minimum.setStyleSheet("background: rgb(255, 196, 48);")
        self.minimum.setObjectName("minimum")
        self.horizontalLayout.addWidget(self.minimum)
        self.close = QtWidgets.QPushButton(self.window_buttons)
        self.close.setMinimumSize(QtCore.QSize(18, 18))
        self.close.setMaximumSize(QtCore.QSize(18, 18))
        self.close.setStyleSheet("background: rgb(255, 98, 89)")
        self.close.setObjectName("close")
        self.horizontalLayout.addWidget(self.close)
        self.horizontalLayout_2.addWidget(self.window_buttons)
        self.verticalLayout_3.addWidget(self.window)
        self.Form_downbar = QtWidgets.QWidget(self.main_widget)
        self.Form_downbar.setEnabled(True)
        self.Form_downbar.setMinimumSize(QtCore.QSize(500, 120))
        self.Form_downbar.setMaximumSize(QtCore.QSize(500, 16777215))
        self.Form_downbar.setAutoFillBackground(False)
        self.Form_downbar.setStyleSheet("/* Form downloader margin */\n"
"#Form_downbar {\n"
"    margin:0px;\n"
"    padding:20px\n"
"}\n"
"\n"
"/* Download Grid */\n"
"#Form_download_grid {\n"
"    margin:0px;\n"
"    padding:0px\n"
"}\n"
"\n"
"/* Download Button */\n"
"#Form_downbar_get {\n"
"    border-radius:15px; \n"
"    width: 50px; \n"
"    height: 30px;\n"
"    background:rgb(52, 120, 245); \n"
"    font: 18px \"나눔스퀘어 ExtraBold\"; \n"
"    color: #ffffff\n"
"}\n"
"#Form_downbar_get:hover {\n"
"    background:rgba(52, 120, 245, 100);\n"
"    color: #ffffff\n"
"}\n"
"\n"
"/**/\n"
"#Form_id {\n"
"    font: 18px \"나눔스퀘어 Bold\"\n"
"}\n"
"#Form_info {\n"
"    font: 14px \"나눔스퀘어\"; \n"
"    color: #989799\n"
"}\n"
"#Form_icon {\n"
"    border-radius: 5px; \n"
"    border: 1px solid #eeeef0;\n"
"    background: #f7f7f7;\n"
"    margin: 5px;\n"
"}")
        self.Form_downbar.setObjectName("Form_downbar")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.Form_downbar)
        self.verticalLayout.setContentsMargins(60, 20, 60, 10)
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.FormName = QtWidgets.QLabel(self.Form_downbar)
        self.FormName.setMaximumSize(QtCore.QSize(16777215, 40))
        self.FormName.setObjectName("FormName")
        self.verticalLayout.addWidget(self.FormName)
        self.Form_downbar_grid = QtWidgets.QWidget(self.Form_downbar)
        self.Form_downbar_grid.setObjectName("Form_downbar_grid")
        self.Searchbar_layout = QtWidgets.QHBoxLayout(self.Form_downbar_grid)
        self.Searchbar_layout.setContentsMargins(0, 0, 0, 0)
        self.Searchbar_layout.setSpacing(0)
        self.Searchbar_layout.setObjectName("Searchbar_layout")
        self.Form_icon = QtWidgets.QLabel(self.Form_downbar_grid)
        self.Form_icon.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Form_icon.sizePolicy().hasHeightForWidth())
        self.Form_icon.setSizePolicy(sizePolicy)
        self.Form_icon.setMinimumSize(QtCore.QSize(60, 0))
        self.Form_icon.setMaximumSize(QtCore.QSize(60, 60))
        self.Form_icon.setText("")
        self.Form_icon.setPixmap(QtGui.QPixmap(":/img/assets/Microsoft_Excel-Logo.wine.svg"))
        self.Form_icon.setScaledContents(True)
        self.Form_icon.setIndent(-1)
        self.Form_icon.setObjectName("Form_icon")
        self.Searchbar_layout.addWidget(self.Form_icon)
        self.Form_downbar_info = QtWidgets.QWidget(self.Form_downbar_grid)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Form_downbar_info.sizePolicy().hasHeightForWidth())
        self.Form_downbar_info.setSizePolicy(sizePolicy)
        self.Form_downbar_info.setObjectName("Form_downbar_info")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.Form_downbar_info)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.Form_id = QtWidgets.QLabel(self.Form_downbar_info)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Form_id.sizePolicy().hasHeightForWidth())
        self.Form_id.setSizePolicy(sizePolicy)
        self.Form_id.setObjectName("Form_id")
        self.verticalLayout_4.addWidget(self.Form_id)
        self.Form_info = QtWidgets.QLabel(self.Form_downbar_info)
        self.Form_info.setObjectName("Form_info")
        self.verticalLayout_4.addWidget(self.Form_info)
        self.Searchbar_layout.addWidget(self.Form_downbar_info)
        self.Form_downbar_get = QtWidgets.QPushButton(self.Form_downbar_grid)
        self.Form_downbar_get.setMinimumSize(QtCore.QSize(70, 0))
        self.Form_downbar_get.setMaximumSize(QtCore.QSize(70, 16777215))
        self.Form_downbar_get.setObjectName("Form_downbar_get")
        self.Searchbar_layout.addWidget(self.Form_downbar_get)
        self.verticalLayout.addWidget(self.Form_downbar_grid)
        self.verticalLayout_3.addWidget(self.Form_downbar)
        self.Macro = QtWidgets.QWidget(self.main_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Macro.sizePolicy().hasHeightForWidth())
        self.Macro.setSizePolicy(sizePolicy)
        self.Macro.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Macro.setStyleSheet("/* Macro grid */\n"
"#Macrobar_grid {margin: 0px}\n"
"\n"
"/* Macro buttons in grid */\n"
"#Macrobar_grid .QWidget {\n"
"    margin: 0px; \n"
"    border-radius: 25px; \n"
"    background: rgba(230, 111, 85, 255);\n"
"}\n"
"#Macrobar_grid .QWidget:hover {\n"
"    background:  rgba(230, 111, 85, 200)\n"
"}\n"
"#Macrobar_grid .QWidget .QLabel {\n"
"    font: 18px \"나눔스퀘어 Bold\"; \n"
"    color: white;\n"
"}\n"
"#Macrobar_grid .QWidget .QPushButton {\n"
"    background: transparent;\n"
"}\n"
"\n"
"\n"
"/* Macro scrollbar */\n"
"#Macrobar_scroll {\n"
"    margin: 0px; \n"
"    padding: 0px; \n"
"    border: 0px solid;\n"
"}\n"
".QScrollArea .QScrollBar:vertical {\n"
"    border: 0px solid #c3c3c3;\n"
"    background:white;\n"
"    width:10px;\n"
"    margin: 0px 0px 0px 2px;\n"
"}\n"
".QScrollArea .QScrollBar::handle:vertical {\n"
"    min-height: 0px;\n"
"    border: 0px solid red;\n"
"    border-radius: 4px;\n"
"    background-color: #c3c3c3;\n"
"}\n"
".QScrollArea .QScrollBar::add-line:vertical {       \n"
"    height: 0px;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"}\n"
".QScrollArea .QScrollBar::sub-line:vertical {\n"
"    height: 0 px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"}")
        self.Macro.setObjectName("Macro")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.Macro)
        self.verticalLayout_2.setContentsMargins(60, 20, 60, 0)
        self.verticalLayout_2.setSpacing(10)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.MacroName = QtWidgets.QLabel(self.Macro)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MacroName.sizePolicy().hasHeightForWidth())
        self.MacroName.setSizePolicy(sizePolicy)
        self.MacroName.setMaximumSize(QtCore.QSize(16777215, 40))
        self.MacroName.setObjectName("MacroName")
        self.verticalLayout_2.addWidget(self.MacroName)
        self.Macrobar_scroll = QtWidgets.QScrollArea(self.Macro)
        self.Macrobar_scroll.setStyleSheet("")
        self.Macrobar_scroll.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.Macrobar_scroll.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.Macrobar_scroll.setWidgetResizable(True)
        self.Macrobar_scroll.setObjectName("Macrobar_scroll")
        self.Macrobar_grid = QtWidgets.QWidget()
        self.Macrobar_grid.setGeometry(QtCore.QRect(0, 0, 370, 538))
        self.Macrobar_grid.setStyleSheet("")
        self.Macrobar_grid.setObjectName("Macrobar_grid")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.Macrobar_grid)
        self.gridLayout_5.setContentsMargins(0, 0, 10, 0)
        self.gridLayout_5.setSpacing(10)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.Macro_items_1 = QtWidgets.QWidget(self.Macrobar_grid)
        self.Macro_items_1.setMinimumSize(QtCore.QSize(180, 130))
        self.Macro_items_1.setMaximumSize(QtCore.QSize(180, 130))
        self.Macro_items_1.setStyleSheet("#Macrobar_grid .QWidget {background: rgba(230, 111, 85, 255);}\n"
"#Macrobar_grid .QWidget:hover {background:  rgba(230, 111, 85, 200)}")
        self.Macro_items_1.setObjectName("Macro_items_1")
        self.Macro_push_1 = QtWidgets.QPushButton(self.Macro_items_1)
        self.Macro_push_1.setGeometry(QtCore.QRect(0, 0, 180, 130))
        self.Macro_push_1.setMinimumSize(QtCore.QSize(180, 130))
        self.Macro_push_1.setMaximumSize(QtCore.QSize(180, 130))
        self.Macro_push_1.setStyleSheet("")
        self.Macro_push_1.setText("")
        self.Macro_push_1.setObjectName("Macro_push_1")
        self.Macro_labels_1 = QtWidgets.QLabel(self.Macro_items_1)
        self.Macro_labels_1.setEnabled(False)
        self.Macro_labels_1.setGeometry(QtCore.QRect(10, 70, 160, 21))
        self.Macro_labels_1.setIndent(-1)
        self.Macro_labels_1.setObjectName("Macro_labels_1")
        self.Macro_describes_1 = QtWidgets.QLabel(self.Macro_items_1)
        self.Macro_describes_1.setEnabled(False)
        self.Macro_describes_1.setGeometry(QtCore.QRect(10, 95, 160, 21))
        self.Macro_describes_1.setStyleSheet(".QLabel {font: 13px \"나눔스퀘어\"; color: white;}")
        self.Macro_describes_1.setIndent(-1)
        self.Macro_describes_1.setObjectName("Macro_describes_1")
        self.Macro_icon_1 = QtWidgets.QLabel(self.Macro_items_1)
        self.Macro_icon_1.setEnabled(False)
        self.Macro_icon_1.setGeometry(QtCore.QRect(12, 12, 28, 30))
        self.Macro_icon_1.setStyleSheet("border-image: url(:/img/assets/user-solid.svg);")
        self.Macro_icon_1.setText("")
        self.Macro_icon_1.setScaledContents(True)
        self.Macro_icon_1.setIndent(-1)
        self.Macro_icon_1.setObjectName("Macro_icon_1")
        self.Macro_labels_1.raise_()
        self.Macro_describes_1.raise_()
        self.Macro_icon_1.raise_()
        self.Macro_push_1.raise_()
        self.gridLayout_5.addWidget(self.Macro_items_1, 0, 0, 1, 1)
        self.Macrobar_scroll.setWidget(self.Macrobar_grid)
        self.verticalLayout_2.addWidget(self.Macrobar_scroll)
        self.verticalLayout_3.addWidget(self.Macro)
        self.Tutorial = QtWidgets.QWidget(self.main_widget)
        self.Tutorial.setEnabled(True)
        self.Tutorial.setMinimumSize(QtCore.QSize(498, 140))
        self.Tutorial.setMaximumSize(QtCore.QSize(240, 140))
        self.Tutorial.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.Tutorial.setStyleSheet("#TutorialName {\n"
"    font: 18px;\n"
"    color: rgb(80,80,80)\n"
"}\n"
"#Tutorial_widget {\n"
"    background:rgb(52, 120, 245);\n"
"    border-radius:30px;\n"
"    background-repeat:none;\n"
"}\n"
"#Tutorial_widget:hover  {\n"
"    background:rgba(52, 120, 245, 100)\n"
"}\n"
"\n"
"/* Tutorial button inside */\n"
"#Tutorial_grid {\n"
"    margin:0px; \n"
"    padding:0px; \n"
"    background:transparent;\n"
"}\n"
"#Tutorial_info_title {\n"
"    color:white;\n"
"    font:18px; \n"
"    background:transparent\n"
"}\n"
".QPushButton {background:transparent}")
        self.Tutorial.setObjectName("Tutorial")
        self.TutorialName = QtWidgets.QLabel(self.Tutorial)
        self.TutorialName.setGeometry(QtCore.QRect(50, 17, 401, 33))
        self.TutorialName.setObjectName("TutorialName")
        self.Tutorial_dev = QtWidgets.QLabel(self.Tutorial)
        self.Tutorial_dev.setGeometry(QtCore.QRect(316, 20, 141, 20))
        self.Tutorial_dev.setStyleSheet("font: 10px \"나눔스퀘어\";\n"
"color: rgb(80,80,80)")
        self.Tutorial_dev.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Tutorial_dev.setObjectName("Tutorial_dev")
        self.Tutorial_subbackground = QtWidgets.QLabel(self.Tutorial)
        self.Tutorial_subbackground.setGeometry(QtCore.QRect(14, 0, 471, 191))
        self.Tutorial_subbackground.setStyleSheet("background: rgb(223, 223, 224); border-radius: 20px;")
        self.Tutorial_subbackground.setText("")
        self.Tutorial_subbackground.setObjectName("Tutorial_subbackground")
        self.Tutorial_background = QtWidgets.QLabel(self.Tutorial)
        self.Tutorial_background.setGeometry(QtCore.QRect(4, 10, 491, 191))
        self.Tutorial_background.setStyleSheet("background: rgb(238, 238, 239); border-radius: 20px;")
        self.Tutorial_background.setText("")
        self.Tutorial_background.setObjectName("Tutorial_background")
        self.Tutorial_widget = QtWidgets.QWidget(self.Tutorial)
        self.Tutorial_widget.setGeometry(QtCore.QRect(120, 60, 251, 61))
        self.Tutorial_widget.setObjectName("Tutorial_widget")
        self.Tutorial_grid = QtWidgets.QWidget(self.Tutorial_widget)
        self.Tutorial_grid.setGeometry(QtCore.QRect(27, 10, 200, 40))
        self.Tutorial_grid.setMinimumSize(QtCore.QSize(0, 40))
        self.Tutorial_grid.setMaximumSize(QtCore.QSize(240, 40))
        self.Tutorial_grid.setStyleSheet("")
        self.Tutorial_grid.setObjectName("Tutorial_grid")
        self.Searchbar_layout_3 = QtWidgets.QHBoxLayout(self.Tutorial_grid)
        self.Searchbar_layout_3.setContentsMargins(0, 0, 0, 0)
        self.Searchbar_layout_3.setSpacing(0)
        self.Searchbar_layout_3.setObjectName("Searchbar_layout_3")
        self.Tutorial_info_logo = QtWidgets.QLabel(self.Tutorial_grid)
        self.Tutorial_info_logo.setEnabled(True)
        self.Tutorial_info_logo.setMaximumSize(QtCore.QSize(30, 30))
        self.Tutorial_info_logo.setStyleSheet("border-image: url(:/img/circle-info-solid.svg)")
        self.Tutorial_info_logo.setText("")
        self.Tutorial_info_logo.setObjectName("Tutorial_info_logo")
        self.Searchbar_layout_3.addWidget(self.Tutorial_info_logo)
        self.Tutorial_info_title = QtWidgets.QLabel(self.Tutorial_grid)
        self.Tutorial_info_title.setEnabled(True)
        self.Tutorial_info_title.setMaximumSize(QtCore.QSize(160, 40))
        self.Tutorial_info_title.setStyleSheet("margin-left: 2px;")
        self.Tutorial_info_title.setAlignment(QtCore.Qt.AlignCenter)
        self.Tutorial_info_title.setObjectName("Tutorial_info_title")
        self.Searchbar_layout_3.addWidget(self.Tutorial_info_title)
        self.Tutorial_Push = QtWidgets.QPushButton(self.Tutorial_widget)
        self.Tutorial_Push.setGeometry(QtCore.QRect(0, 0, 251, 60))
        self.Tutorial_Push.setMinimumSize(QtCore.QSize(0, 60))
        self.Tutorial_Push.setText("")
        self.Tutorial_Push.setObjectName("Tutorial_Push")
        self.Tutorial_subbackground.raise_()
        self.Tutorial_background.raise_()
        self.TutorialName.raise_()
        self.Tutorial_widget.raise_()
        self.Tutorial_dev.raise_()
        self.verticalLayout_3.addWidget(self.Tutorial)
        MainApp.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainApp)
        QtCore.QMetaObject.connectSlotsByName(MainApp)

    def retranslateUi(self, MainApp):
        _translate = QtCore.QCoreApplication.translate
        MainApp.setWindowTitle(_translate("MainApp", "MainWindow"))
        self.infobox_title.setText(_translate("MainApp", "업로드를 실행할 수 없습니다."))
        self.infobox_confirm.setText(_translate("MainApp", "OK"))
        self.infobox_detail.setText(_translate("MainApp", "나이스가 켜져 있는지 확인해주세요."))
        self.minimum.setText(_translate("MainApp", ""))
        self.close.setText(_translate("MainApp", ""))
        self.FormName.setText(_translate("MainApp", "다운로드"))
        self.Form_id.setText(_translate("MainApp", "Macro Forms"))
        self.Form_info.setText(_translate("MainApp", "업로드를 위한 양식을 다운로드하세요"))
        self.Form_downbar_get.setText(_translate("MainApp", "GET"))
        self.MacroName.setText(_translate("MainApp", "손쉬운 업로드 갤러리"))
        self.Macro_labels_1.setText(_translate("MainApp", "행발:종합의견"))
        self.Macro_describes_1.setText(_translate("MainApp", "학기말 종합 평가"))
        self.TutorialName.setText(_translate("MainApp", "어떻게 사용해야 하나요?"))
        self.Tutorial_dev.setText(_translate("MainApp", "Contributor    Gonyo"))
        self.Tutorial_info_title.setText(_translate("MainApp", "사용법 확인하기"))
from src.views.ui import main_rc